import Head from 'next/head';
import Image from 'next/image';
import Message from '../components/Message';
import { useEffect,useState } from 'react';
import { db } from '../utils/firebase';
import { collection, getDocs, onSnapshot, orderBy, query } from 'firebase/firestore';
export default function Home() {

  //Create a state with all the posts
  const [allPosts, setAllPosts] = useState([]);
  const getPosts = async () => {
    const collectionRef = collection(db,'posts');
    const q = query(collectionRef, orderBy('timeStamp','desc'));
    // Realtime update
    const unsubscribe = onSnapshot(q, (snapShot) => {
      setAllPosts(snapShot.docs.map((doc) => ({...doc.data(),id : doc.id})));
    });
    return unsubscribe;
  };

  useEffect(() => {
    getPosts();
  },[]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='my-12 text-lg font-medium'>
        <h2>See what other people are saying</h2>
        {allPosts.map((post) => (
          <Message key={post.id} {...post} />
        ))}
      </div>
   </div>
  )
}
